[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1"
chrono = { version = "0.4.38", features = ["serde"] }
thiserror = "1.0"
futures = "0.3.30"
tokio = { version = "1.0", features = ["full"] }
log = "0.4.27"
